// --- Autogenerated file ---
                // ----- Do not modify! -----

                namespace SPT.Common
                {
                public static class SPTPluginInfo
                {
                public const string PLUGIN_VERSION = "4.0.13";
                }
                }
